config/routes.rb
Xfici::Application.routes.draw do

  devise_for :users

  resources :users, only: [:show, :index, :destroy, :edit, :update] do
    member do
      get :friends, :pending_friends, :requested_friends
    end
  end

  resources :microposts, only: [:create, :destroy, :update] do
    resources :comments
  end

  resources :friendships

  root to: 'static_pages#home'

  match '/help', to: 'static_pages#help'

  match '/about', to: 'static_pages#about'

  match '/contact', to: 'static_pages#contact'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<%= link_to avatar_for(feed_item.user, 80), feed_item.user %>
	<span class="user">
		<%= link_to feed_item.user.name, feed_item.user %>
	</span>
	<span class="content">
	  <% if current_user != feed_item.user %>
	      <pre><%= feed_item.content %></pre>
	  <% else %>
	      <pre><%=best_in_place feed_item, :content %></pre>
	  <% end %>
	</span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
	</span>
	<%= render "shared/vote", object: feed_item %>
	<% if current_user == feed_item.user %>
		<span class="deleteLink">
			<%= link_to "delete", feed_item, method: :delete,
			remote: true,
			title: feed_item.content %>
		</span>
	<% end %>
	<%= render "comments/comment_input", object: feed_item %>
	<%= render "comments/comment", object: feed_item %>
</li>

app/views/shared/_like_links.html.erb
<%= form_form (micropost, remote: true, html:{ method: :put}) do |f| %>
	<%= link_to "Like", "#", data: {vote: 'like', user: current_user.id}, class: "like-post-link" %>
	<%= link_to "Dont Like", "#", data: {vote: 'like', user: current_user.id}, class: "dontlike-post-link" %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.text_area :content, placeholder: "Compose new micropost..." %>
	</div>
	<%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= friends_user_path(@user) %>">
		<strong id="Friends" class="stat">
			<%= @user.friends.count %>
		</strong>
		Friends
	</a>
	<a href="<%= pending_friends_user_path(@user) %>">
		<strong id="PendingFriends" class="stat">
			<%= @user.pending_friends.count %>
		</strong>
		Pending
	</a>
	<a href="<%= requested_friends_user_path(@user) %>">
		<strong id="RequestedFriends" class="stat">
			<%= @user.requested_friends.count %>
		</strong>
		Requested
	</a>
</div>

app/views/shared/_unvoted_links.html.erb
<%= form_for(object) do |f| %>
	<%= link_to "Like", micropost_path(object, {vote: :true}), remote:true, method: :put, 
		class: "like-post-link" %>
	- 
	<%= link_to object.get_likes.size, "#", class: "count-like-post-link" %>
	|
	<%= link_to "Don't Like", micropost_path(object, {vote: :false}), remote:true, method: :put, 
		class: "dislike-post-link" %>
	-
	<%= link_to object.get_dislikes.size, "#", class: "count-dislike-post-link" %>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>"></a>
<h1>
	<%= current_user.name %>
</h1>
<div>
	  <%= avatar_for(current_user, 400) %>
</div>
<span>
	<%= link_to "view my profile", current_user %>
</span>
<span>
	<%= pluralize(current_user.microposts.count, "micropost") %>
</span>

app/views/shared/_users_avatars.html.erb
<% if object.any? %>
	<div class="user_avatars">
		<% object.each do |user| %>
			<%= link_to avatar_for(user, 30), user %>
		<% end %>
	</div>
<% end %>

app/views/shared/_vote.html.erb
<div class="vote_form">
	<%= form_for(object) do |f| %>
		<% if current_user.voted_for? object %>
			<%= render 'shared/voted_links', object: object %>
		<% else %>
			<%= render 'shared/unvoted_links', object: object %>
		<% end%>
	<% end %>
</div>

app/views/shared/_voted_links.html.erb
<%= form_for(object) do |f| %>
	<% if current_user.voted_as_when_voted_for object %>
		<%= link_to "Unlike", micropost_path(object, {vote: 'cancel'}), remote: true, method: :put, 
			class: "unlike-post-link" %>
		- 
		<%= link_to object.get_likes.size, "#", class: "count-like-post-link" %>
		|
		 Don't Like
		-
		<%= link_to object.get_dislikes.size, "#", class: "count-dislike-post-link" %>
	<% else %>
		Like
		- 
		<%= link_to object.get_likes.size, "#", class: "count-like-post-link" %>
		|
		<%= link_to "Cancel Don't Like", micropost_path(object, {vote: 'cancel'}), remote: true, method: :put,
			 class: "undislike-post-link" %>
		-
		<%= link_to object.get_dislikes.size, "#", class: "count-dislike-post-link" %>
	<% end %>
<% end %>