config/routes.rb
Xfici::Application.routes.draw do

  devise_for :users

  resources :users, only: [:show, :index, :destroy, :edit, :update] do
    member do
      get :friends, :pending_friends, :requested_friends
    end
  end

  resources :microposts, only: [:create, :destroy, :update] do
    resources :comments
  end

  resources :friendships

  root to: 'static_pages#home'

  match '/help', to: 'static_pages#help'

  match '/about', to: 'static_pages#about'

  match '/contact', to: 'static_pages#contact'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<%= link_to "xFICI", root_path %> by Ariel Umansky	
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><a href="http://news.railstutorial.org/">News</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "xfici", '#', id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Help", help_path %></li>
					<% if user_signed_in? %>
						<li><%= link_to "Users", users_path %></li>
						<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								Account <b class="caret"></b>
							</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Profile", user_path(current_user) %></li>
							<li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
							<li><%= link_to "Manage Account", edit_user_registration_path(current_user) %></li>
							<li class="divider"></li>
							<li>
								<%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
							</li>
						</ul>
					</li>
					<% else %>
						<li><%= link_to "Sign in", new_user_session_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
		  <%= stylesheet_link_tag    "application", :media => "all" %>
		  <%= javascript_include_tag "application" %>
		  <%= csrf_meta_tags %>
		  <%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			
			<% if notice %>
  				<p class="alert alert-success"><%= notice %></p>
			<% end %>
			<% if alert %>
  				<p class="alert alert-danger"><%= alert %></p>
			<% end %>

			<%= yield %>

			<%= render 'layouts/footer' %>

			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>